apiVersion: v2
description: A Helm chart for EDP Component Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: edp-component-operator
type: application
version: 0.7.0-SNAPSHOT
appVersion: 0.7.0-SNAPSHOT
maintainers:
  - name: EPAM EDP Team
sources:
  - https://github.com/epam/edp-component-operator
